global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: data-core-api
    static_configs:
      - targets: ["data-core-api:8000"]
    metrics_path: /metrics

  - job_name: poupi-baby-api
    static_configs:
      - targets: ["poupi-baby-api:3001"]
    metrics_path: /metrics
