DEFAULT_ENTITY_RELATIONSHIPS = [
    {
        "module": "ecommerce",
        "source_entity": "raw_collections:scrapedProduct",
        "target_entity": "normalized_products",
        "relationship_type": "normalizes_to",
        "description": "Poupi/e-commerce RAW product payloads normalize into product snapshots.",
    },
    {
        "module": "ecommerce",
        "source_entity": "normalized_products",
        "target_entity": "product_price_analytics",
        "relationship_type": "analytics_input",
        "description": "Normalized product price snapshots feed product price analytics.",
    },
    {
        "module": "real_estate",
        "source_entity": "raw_collections:realEstateHtmlPage",
        "target_entity": "normalized_real_estate_listings",
        "relationship_type": "normalizes_to",
        "description": "Collected listing HTML normalizes into real estate listing snapshots.",
    },
    {
        "module": "real_estate",
        "source_entity": "normalized_real_estate_listings",
        "target_entity": "real_estate_analytics",
        "relationship_type": "analytics_input",
        "description": "Normalized listings feed price/m2 and opportunity analytics.",
    },
    {
        "module": "sports_odds",
        "source_entity": "sports_events",
        "target_entity": "sports_markets",
        "relationship_type": "has_many",
        "description": "A sports event can contain multiple betting markets.",
    },
    {
        "module": "sports_odds",
        "source_entity": "sports_markets",
        "target_entity": "sports_odds_snapshots",
        "relationship_type": "has_many",
        "description": "Each market can have multiple historical odds snapshots.",
    },
    {
        "module": "sports_odds",
        "source_entity": "normalized_sports_odds",
        "target_entity": "sports_odds_analytics",
        "relationship_type": "analytics_input",
        "description": "Normalized odds snapshots feed line movement analytics.",
    },
    {
        "module": "crypto",
        "source_entity": "raw_collections:cryptoPriceSnapshot",
        "target_entity": "normalized_crypto_snapshots",
        "relationship_type": "normalizes_to",
        "description": "Crypto market price payloads normalize into price snapshots.",
    },
    {
        "module": "trading",
        "source_entity": "raw_collections:marketCandle",
        "target_entity": "normalized_market_candles",
        "relationship_type": "normalizes_to",
        "description": "OHLCV payloads normalize into market candles used by trading analytics.",
    },
]
