DEFAULT_SCHEMA_DOCUMENTATION = [
    {
        "module": "ecommerce",
        "schema_type": "raw",
        "schema_name": "scrapedProduct",
        "schema_version": "1.0.0",
        "description": "Schema legado do Poupi Baby usado por scrapers e-commerce.",
        "fields_json": {
            "success": "boolean",
            "name": "string|null",
            "price": "number|null",
            "availability": "boolean|string|null",
            "store": "string|null",
            "imageUrl": "string|null",
            "error": "string|null",
            "scrapedAt": "datetime|string",
        },
        "examples_json": {
            "scrapedProduct": {
                "success": True,
                "name": "Produto exemplo",
                "price": 129.9,
                "availability": True,
                "store": "drogasil",
            }
        },
        "validation_rules_json": ["payload must contain scrapedProduct or product-like fields"],
        "relationships_json": ["raw_collections -> normalized_products"],
    },
    {
        "module": "sports_odds",
        "schema_type": "raw",
        "schema_name": "genericOddsSnapshot",
        "schema_version": "1.0.0",
        "description": "Payload simples de odds usado por collectors genéricos e testes.",
        "fields_json": {
            "event_id": "string",
            "sport": "string",
            "market": "string",
            "selection": "string",
            "odd": "number",
        },
        "examples_json": {"event_id": "demo-match-1", "market": "1x2", "selection": "home_win", "odd": 1.95},
        "validation_rules_json": ["odd must be positive when present"],
        "relationships_json": ["raw_collections -> normalized_sports_odds"],
    },
    {
        "module": "real_estate",
        "schema_type": "raw",
        "schema_name": "realEstateHtmlPage",
        "schema_version": "1.0.0",
        "description": "HTML renderizado de páginas de detalhe de imóveis.",
        "fields_json": {"raw_content": "html string", "target_url": "listing detail URL"},
        "examples_json": {"target_url": "https://www.apolar.com.br/..."},
        "validation_rules_json": ["raw_content should be non-empty HTML"],
        "relationships_json": ["raw_collections -> normalized_real_estate_listings"],
    },
    {
        "module": "crypto",
        "schema_type": "raw",
        "schema_name": "cryptoPriceSnapshot",
        "schema_version": "1.0.0",
        "description": "Snapshot de preço de ativo cripto.",
        "fields_json": {"symbol": "string", "price": "number", "volume": "number|null", "market_cap": "number|null"},
        "examples_json": {"symbol": "BTC-BRL", "price": 350000.0},
        "validation_rules_json": ["symbol should be present"],
        "relationships_json": ["raw_collections -> normalized_crypto_snapshots"],
    },
    {
        "module": "trading",
        "schema_type": "raw",
        "schema_name": "marketCandle",
        "schema_version": "1.0.0",
        "description": "Payload OHLCV usado por cripto/trading.",
        "fields_json": {
            "symbol": "string",
            "timeframe": "string",
            "timestamp": "datetime|string",
            "open": "number",
            "high": "number",
            "low": "number",
            "close": "number",
            "volume": "number",
        },
        "examples_json": {"symbol": "BTC/USDT", "timeframe": "1m", "close": 100000.0},
        "validation_rules_json": ["open/high/low/close should be numeric"],
        "relationships_json": ["raw_collections -> normalized_market_candles"],
    },
]
