DEFAULT_SCHEMA_DOCUMENTATION = [
    {
        "module": "ecommerce",
        "schema_type": "raw",
        "schema_name": "scrapedProduct",
        "schema_version": "1.0.0",
        "description": "Schema legado do Poupi Baby usado por scrapers e-commerce.",
        "fields_json": {
            "success": "boolean",
            "name": "string|null",
            "price": "number|null",
            "availability": "boolean|string|null",
            "store": "string|null",
            "imageUrl": "string|null",
            "error": "string|null",
            "scrapedAt": "datetime|string",
        },
        "examples_json": {
            "scrapedProduct": {
                "success": True,
                "name": "Produto exemplo",
                "price": 129.9,
                "availability": True,
                "store": "drogasil",
            }
        },
        "validation_rules_json": ["payload must contain scrapedProduct or product-like fields"],
        "relationships_json": ["raw_collections -> normalized_products"],
    },
    {
        "module": "ecommerce",
        "schema_type": "raw",
        "schema_name": "genericProduct",
        "schema_version": "1.0.0",
        "description": "Payload generico de produto usado por collectors e-commerce nativos do Data Core.",
        "fields_json": {
            "title": "string",
            "price": "number|null",
            "currency": "string|null",
            "availability": "string|boolean|null",
            "store_name": "string|null",
            "brand": "string|null",
            "url": "string|null",
        },
        "examples_json": {
            "title": "Produto exemplo",
            "price": 19.9,
            "currency": "BRL",
            "availability": "in_stock",
            "store_name": "generic_marketplace",
        },
        "validation_rules_json": ["title should be present", "price should be greater than zero when present"],
        "relationships_json": ["raw_collections -> normalized_products -> product_price_analytics"],
    },
    {
        "module": "sports_odds",
        "schema_type": "raw",
        "schema_name": "genericOddsSnapshot",
        "schema_version": "1.0.0",
        "description": "Payload simples de odds usado por collectors genéricos e testes.",
        "fields_json": {
            "event_id": "string",
            "sport": "string",
            "market": "string",
            "selection": "string",
            "odd": "number",
        },
        "examples_json": {"event_id": "demo-match-1", "market": "1x2", "selection": "home_win", "odd": 1.95},
        "validation_rules_json": ["odd must be positive when present"],
        "relationships_json": ["raw_collections -> normalized_sports_odds"],
    },
    {
        "module": "sports_odds",
        "schema_type": "raw",
        "schema_name": "nbaOddsSnapshot",
        "schema_version": "1.0.0",
        "description": "Snapshot de odds de NBA preparado para mercados pre-jogo.",
        "fields_json": {
            "event_external_id": "string",
            "sport": "basketball",
            "league": "NBA",
            "sportsbook": "string",
            "home_team": "string",
            "away_team": "string",
            "start_time": "datetime|string|null",
            "market_type": "moneyline|spread|totals|player_prop",
            "selection": "string",
            "handicap": "number|null",
            "odd": "number",
            "implied_probability": "number|null",
        },
        "examples_json": {
            "event_external_id": "nba-2026-lal-bos",
            "sport": "basketball",
            "league": "NBA",
            "sportsbook": "generic_bookmaker",
            "home_team": "LAL",
            "away_team": "BOS",
            "market_type": "moneyline",
            "selection": "home",
            "odd": 1.91,
        },
        "validation_rules_json": ["odd must be greater than 1", "event and market identity should be present"],
        "relationships_json": ["raw_collections -> normalized_sports_odds -> sports_odds_analytics"],
    },
    {
        "module": "real_estate",
        "schema_type": "raw",
        "schema_name": "realEstateHtmlPage",
        "schema_version": "1.0.0",
        "description": "HTML renderizado de páginas de detalhe de imóveis.",
        "fields_json": {"raw_content": "html string", "target_url": "listing detail URL"},
        "examples_json": {"target_url": "https://www.apolar.com.br/..."},
        "validation_rules_json": ["raw_content should be non-empty HTML"],
        "relationships_json": ["raw_collections -> normalized_real_estate_listings"],
    },
    {
        "module": "real_estate",
        "schema_type": "normalized",
        "schema_name": "realEstateListing",
        "schema_version": "1.0.0",
        "description": "Entidade normalizada de anuncio imobiliario para historico e analytics.",
        "fields_json": {
            "external_id": "string|null",
            "url": "string|null",
            "title": "string|null",
            "property_type": "string|null",
            "purpose": "sale|rent|null",
            "price": "number|null",
            "city": "string|null",
            "neighborhood": "string|null",
            "area_m2": "number|null",
            "bedrooms": "integer|null",
            "bathrooms": "integer|null",
            "parking_spaces": "integer|null",
        },
        "examples_json": {
            "title": "Apartamento no Agua Verde",
            "purpose": "sale",
            "price": 550000,
            "city": "Curitiba",
            "neighborhood": "Agua Verde",
            "area_m2": 72,
        },
        "validation_rules_json": ["city should be present", "price should be greater than zero when present"],
        "relationships_json": ["normalized_real_estate_listings -> real_estate_analytics"],
    },
    {
        "module": "crypto",
        "schema_type": "raw",
        "schema_name": "cryptoPriceSnapshot",
        "schema_version": "1.0.0",
        "description": "Snapshot de preço de ativo cripto.",
        "fields_json": {"symbol": "string", "price": "number", "volume": "number|null", "market_cap": "number|null"},
        "examples_json": {"symbol": "BTC-BRL", "last_price": 350000.0, "volume_24h": 123.45},
        "validation_rules_json": ["symbol should be present", "price/last/last_price should be greater than zero"],
        "relationships_json": ["raw_collections -> normalized_crypto_snapshots"],
    },
    {
        "module": "trading",
        "schema_type": "raw",
        "schema_name": "marketCandle",
        "schema_version": "1.0.0",
        "description": "Payload OHLCV usado por cripto/trading.",
        "fields_json": {
            "symbol": "string",
            "timeframe": "string",
            "timestamp": "datetime|string",
            "open": "number",
            "high": "number",
            "low": "number",
            "close": "number",
            "volume": "number",
        },
        "examples_json": {"symbol": "BTC/USDT", "timeframe": "1m", "close": 100000.0},
        "validation_rules_json": ["open/high/low/close should be numeric"],
        "relationships_json": ["raw_collections -> normalized_market_candles"],
    },
]
