"""pipeline layers

Revision ID: 39d33505c86b
Revises: 0003_sports_odds_module
Create Date: 2026-05-13 22:32:29.252428
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision: str = '39d33505c86b'
down_revision: str | None = '0003_sports_odds_module'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('volatility_24h', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('volume_spike_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('trend_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('regime', sa.String(length=80), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_analytics_calculated_at'), 'crypto_analytics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_crypto_analytics_regime'), 'crypto_analytics', ['regime'], unique=False)
    op.create_index(op.f('ix_crypto_analytics_symbol'), 'crypto_analytics', ['symbol'], unique=False)
    op.create_table('raw_collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('request_params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('request_headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=40), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module', 'source_name', 'checksum', name='uq_raw_collection_identity')
    )
    op.create_index(op.f('ix_raw_collections_checksum'), 'raw_collections', ['checksum'], unique=False)
    op.create_index(op.f('ix_raw_collections_collected_at'), 'raw_collections', ['collected_at'], unique=False)
    op.create_index(op.f('ix_raw_collections_content_type'), 'raw_collections', ['content_type'], unique=False)
    op.create_index(op.f('ix_raw_collections_module'), 'raw_collections', ['module'], unique=False)
    op.create_index('ix_raw_collections_module_status', 'raw_collections', ['module', 'processing_status'], unique=False)
    op.create_index(op.f('ix_raw_collections_processing_status'), 'raw_collections', ['processing_status'], unique=False)
    op.create_index('ix_raw_collections_source_collected', 'raw_collections', ['source_name', 'collected_at'], unique=False)
    op.create_index(op.f('ix_raw_collections_source_id'), 'raw_collections', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_collections_source_name'), 'raw_collections', ['source_name'], unique=False)
    op.create_table('sports_odds_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=True),
    sa.Column('market_type', sa.String(length=80), nullable=False),
    sa.Column('selection', sa.String(length=160), nullable=False),
    sa.Column('opening_odd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_odd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('closing_odd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('line_movement', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('clv', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('ev_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sports_odds_analytics_calculated_at'), 'sports_odds_analytics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_sports_odds_analytics_event_id'), 'sports_odds_analytics', ['event_id'], unique=False)
    op.create_index(op.f('ix_sports_odds_analytics_market_type'), 'sports_odds_analytics', ['market_type'], unique=False)
    op.create_index(op.f('ix_sports_odds_analytics_selection'), 'sports_odds_analytics', ['selection'], unique=False)
    op.create_table('trading_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('rsi', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('moving_average_fast', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('moving_average_slow', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('atr', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('trend_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_analytics_calculated_at'), 'trading_analytics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_trading_analytics_symbol'), 'trading_analytics', ['symbol'], unique=False)
    op.create_index(op.f('ix_trading_analytics_timeframe'), 'trading_analytics', ['timeframe'], unique=False)
    op.create_table('normalized_crypto_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_collection_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('change_24h', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analytics_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['raw_collection_id'], ['raw_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_crypto_snapshots_analytics_status'), 'normalized_crypto_snapshots', ['analytics_status'], unique=False)
    op.create_index(op.f('ix_normalized_crypto_snapshots_collected_at'), 'normalized_crypto_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_normalized_crypto_snapshots_raw_collection_id'), 'normalized_crypto_snapshots', ['raw_collection_id'], unique=False)
    op.create_index(op.f('ix_normalized_crypto_snapshots_source'), 'normalized_crypto_snapshots', ['source'], unique=False)
    op.create_index(op.f('ix_normalized_crypto_snapshots_symbol'), 'normalized_crypto_snapshots', ['symbol'], unique=False)
    op.create_table('normalized_market_candles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_collection_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=160), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analytics_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['raw_collection_id'], ['raw_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_norm_market_candle_identity', 'normalized_market_candles', ['source', 'symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_normalized_market_candles_analytics_status'), 'normalized_market_candles', ['analytics_status'], unique=False)
    op.create_index(op.f('ix_normalized_market_candles_raw_collection_id'), 'normalized_market_candles', ['raw_collection_id'], unique=False)
    op.create_index(op.f('ix_normalized_market_candles_source'), 'normalized_market_candles', ['source'], unique=False)
    op.create_index(op.f('ix_normalized_market_candles_symbol'), 'normalized_market_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_normalized_market_candles_timeframe'), 'normalized_market_candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_normalized_market_candles_timestamp'), 'normalized_market_candles', ['timestamp'], unique=False)
    op.create_table('normalized_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_collection_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('canonical_product_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('availability', sa.String(length=80), nullable=True),
    sa.Column('store_name', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('shipping_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analytics_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['raw_collection_id'], ['raw_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_products_analytics_status'), 'normalized_products', ['analytics_status'], unique=False)
    op.create_index(op.f('ix_normalized_products_brand'), 'normalized_products', ['brand'], unique=False)
    op.create_index(op.f('ix_normalized_products_canonical_product_id'), 'normalized_products', ['canonical_product_id'], unique=False)
    op.create_index(op.f('ix_normalized_products_city'), 'normalized_products', ['city'], unique=False)
    op.create_index(op.f('ix_normalized_products_collected_at'), 'normalized_products', ['collected_at'], unique=False)
    op.create_index(op.f('ix_normalized_products_external_id'), 'normalized_products', ['external_id'], unique=False)
    op.create_index(op.f('ix_normalized_products_raw_collection_id'), 'normalized_products', ['raw_collection_id'], unique=False)
    op.create_index(op.f('ix_normalized_products_source_id'), 'normalized_products', ['source_id'], unique=False)
    op.create_index(op.f('ix_normalized_products_state'), 'normalized_products', ['state'], unique=False)
    op.create_index(op.f('ix_normalized_products_store_name'), 'normalized_products', ['store_name'], unique=False)
    op.create_table('normalized_real_estate_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_collection_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('property_type', sa.String(length=80), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('neighborhood', sa.String(length=160), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('area_m2', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('condo_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('iptu', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analytics_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['raw_collection_id'], ['raw_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_norm_real_estate_city_neighborhood', 'normalized_real_estate_listings', ['city', 'neighborhood'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_analytics_status'), 'normalized_real_estate_listings', ['analytics_status'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_city'), 'normalized_real_estate_listings', ['city'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_collected_at'), 'normalized_real_estate_listings', ['collected_at'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_external_id'), 'normalized_real_estate_listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_neighborhood'), 'normalized_real_estate_listings', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_property_type'), 'normalized_real_estate_listings', ['property_type'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_purpose'), 'normalized_real_estate_listings', ['purpose'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_raw_collection_id'), 'normalized_real_estate_listings', ['raw_collection_id'], unique=False)
    op.create_index(op.f('ix_normalized_real_estate_listings_source_id'), 'normalized_real_estate_listings', ['source_id'], unique=False)
    op.create_table('normalized_sports_odds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_collection_id', sa.UUID(), nullable=False),
    sa.Column('sportsbook', sa.String(length=160), nullable=False),
    sa.Column('sport', sa.String(length=80), nullable=False),
    sa.Column('league', sa.String(length=120), nullable=False),
    sa.Column('event_external_id', sa.String(length=255), nullable=True),
    sa.Column('home_team', sa.String(length=160), nullable=False),
    sa.Column('away_team', sa.String(length=160), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('market_type', sa.String(length=80), nullable=False),
    sa.Column('selection', sa.String(length=160), nullable=False),
    sa.Column('handicap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('odd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('implied_probability', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analytics_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['raw_collection_id'], ['raw_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_norm_sports_event_market', 'normalized_sports_odds', ['event_external_id', 'market_type', 'selection'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_analytics_status'), 'normalized_sports_odds', ['analytics_status'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_away_team'), 'normalized_sports_odds', ['away_team'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_collected_at'), 'normalized_sports_odds', ['collected_at'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_event_external_id'), 'normalized_sports_odds', ['event_external_id'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_home_team'), 'normalized_sports_odds', ['home_team'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_league'), 'normalized_sports_odds', ['league'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_market_type'), 'normalized_sports_odds', ['market_type'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_raw_collection_id'), 'normalized_sports_odds', ['raw_collection_id'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_selection'), 'normalized_sports_odds', ['selection'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_sport'), 'normalized_sports_odds', ['sport'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_sportsbook'), 'normalized_sports_odds', ['sportsbook'], unique=False)
    op.create_index(op.f('ix_normalized_sports_odds_start_time'), 'normalized_sports_odds', ['start_time'], unique=False)
    op.create_table('product_price_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('avg_price_7d', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('avg_price_30d', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('min_price_90d', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_price_90d', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['normalized_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_price_analytics_calculated_at'), 'product_price_analytics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_product_price_analytics_product_id'), 'product_price_analytics', ['product_id'], unique=False)
    op.create_table('real_estate_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('price_per_m2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('neighborhood_avg_price_m2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount_vs_neighborhood', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['normalized_real_estate_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_estate_analytics_calculated_at'), 'real_estate_analytics', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_real_estate_analytics_listing_id'), 'real_estate_analytics', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_real_estate_analytics_listing_id'), table_name='real_estate_analytics')
    op.drop_index(op.f('ix_real_estate_analytics_calculated_at'), table_name='real_estate_analytics')
    op.drop_table('real_estate_analytics')
    op.drop_index(op.f('ix_product_price_analytics_product_id'), table_name='product_price_analytics')
    op.drop_index(op.f('ix_product_price_analytics_calculated_at'), table_name='product_price_analytics')
    op.drop_table('product_price_analytics')
    op.drop_index(op.f('ix_normalized_sports_odds_start_time'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_sportsbook'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_sport'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_selection'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_raw_collection_id'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_market_type'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_league'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_home_team'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_event_external_id'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_collected_at'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_away_team'), table_name='normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_sports_odds_analytics_status'), table_name='normalized_sports_odds')
    op.drop_index('ix_norm_sports_event_market', table_name='normalized_sports_odds')
    op.drop_table('normalized_sports_odds')
    op.drop_index(op.f('ix_normalized_real_estate_listings_source_id'), table_name='normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_real_estate_listings_raw_collection_id'), table_name='normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_real_estate_listings_purpose'), table_name='normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_real_estate_listings_property_type'), table_name='normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_real_estate_listings_neighborhood'), table_name='normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_real_estate_listings_external_id'), table_name='normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_real_estate_listings_collected_at'), table_name='normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_real_estate_listings_city'), table_name='normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_real_estate_listings_analytics_status'), table_name='normalized_real_estate_listings')
    op.drop_index('ix_norm_real_estate_city_neighborhood', table_name='normalized_real_estate_listings')
    op.drop_table('normalized_real_estate_listings')
    op.drop_index(op.f('ix_normalized_products_store_name'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_state'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_source_id'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_raw_collection_id'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_external_id'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_collected_at'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_city'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_canonical_product_id'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_brand'), table_name='normalized_products')
    op.drop_index(op.f('ix_normalized_products_analytics_status'), table_name='normalized_products')
    op.drop_table('normalized_products')
    op.drop_index(op.f('ix_normalized_market_candles_timestamp'), table_name='normalized_market_candles')
    op.drop_index(op.f('ix_normalized_market_candles_timeframe'), table_name='normalized_market_candles')
    op.drop_index(op.f('ix_normalized_market_candles_symbol'), table_name='normalized_market_candles')
    op.drop_index(op.f('ix_normalized_market_candles_source'), table_name='normalized_market_candles')
    op.drop_index(op.f('ix_normalized_market_candles_raw_collection_id'), table_name='normalized_market_candles')
    op.drop_index(op.f('ix_normalized_market_candles_analytics_status'), table_name='normalized_market_candles')
    op.drop_index('ix_norm_market_candle_identity', table_name='normalized_market_candles')
    op.drop_table('normalized_market_candles')
    op.drop_index(op.f('ix_normalized_crypto_snapshots_symbol'), table_name='normalized_crypto_snapshots')
    op.drop_index(op.f('ix_normalized_crypto_snapshots_source'), table_name='normalized_crypto_snapshots')
    op.drop_index(op.f('ix_normalized_crypto_snapshots_raw_collection_id'), table_name='normalized_crypto_snapshots')
    op.drop_index(op.f('ix_normalized_crypto_snapshots_collected_at'), table_name='normalized_crypto_snapshots')
    op.drop_index(op.f('ix_normalized_crypto_snapshots_analytics_status'), table_name='normalized_crypto_snapshots')
    op.drop_table('normalized_crypto_snapshots')
    op.drop_index(op.f('ix_trading_analytics_timeframe'), table_name='trading_analytics')
    op.drop_index(op.f('ix_trading_analytics_symbol'), table_name='trading_analytics')
    op.drop_index(op.f('ix_trading_analytics_calculated_at'), table_name='trading_analytics')
    op.drop_table('trading_analytics')
    op.drop_index(op.f('ix_sports_odds_analytics_selection'), table_name='sports_odds_analytics')
    op.drop_index(op.f('ix_sports_odds_analytics_market_type'), table_name='sports_odds_analytics')
    op.drop_index(op.f('ix_sports_odds_analytics_event_id'), table_name='sports_odds_analytics')
    op.drop_index(op.f('ix_sports_odds_analytics_calculated_at'), table_name='sports_odds_analytics')
    op.drop_table('sports_odds_analytics')
    op.drop_index(op.f('ix_raw_collections_source_name'), table_name='raw_collections')
    op.drop_index(op.f('ix_raw_collections_source_id'), table_name='raw_collections')
    op.drop_index('ix_raw_collections_source_collected', table_name='raw_collections')
    op.drop_index(op.f('ix_raw_collections_processing_status'), table_name='raw_collections')
    op.drop_index('ix_raw_collections_module_status', table_name='raw_collections')
    op.drop_index(op.f('ix_raw_collections_module'), table_name='raw_collections')
    op.drop_index(op.f('ix_raw_collections_content_type'), table_name='raw_collections')
    op.drop_index(op.f('ix_raw_collections_collected_at'), table_name='raw_collections')
    op.drop_index(op.f('ix_raw_collections_checksum'), table_name='raw_collections')
    op.drop_table('raw_collections')
    op.drop_index(op.f('ix_crypto_analytics_symbol'), table_name='crypto_analytics')
    op.drop_index(op.f('ix_crypto_analytics_regime'), table_name='crypto_analytics')
    op.drop_index(op.f('ix_crypto_analytics_calculated_at'), table_name='crypto_analytics')
    op.drop_table('crypto_analytics')
    # ### end Alembic commands ###
