"""reconcile model metadata with migration history

Revision ID: 74acc745fb82
Revises: 0105_observer_snapshot_runs
Create Date: 2026-07-02 12:49:38.893530
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "74acc745fb82"
down_revision: str | None = "0105_observer_snapshot_runs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "collected_records",
        "collected_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "collection_runs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "collector_definitions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "collector_definitions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "collector_errors",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "crypto_dataset_quality_scores",
        "integrity_score",
        existing_type=sa.NUMERIC(precision=6, scale=2),
        comment=None,
        existing_comment="0-100 composite score",
        existing_nullable=True,
    )
    op.alter_column(
        "crypto_dataset_quality_scores",
        "staleness_hours",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        comment=None,
        existing_comment="Hours since last candle",
        existing_nullable=True,
    )
    op.alter_column(
        "crypto_dataset_quality_scores",
        "coverage_pct",
        existing_type=sa.NUMERIC(precision=6, scale=2),
        comment=None,
        existing_comment="% of expected candles in 24h",
        existing_nullable=True,
    )
    op.alter_column(
        "crypto_dataset_quality_scores",
        "gap_count",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Missing intervals in last 24h",
        existing_nullable=True,
    )
    op.drop_index("ix_crypto_dq_symbol_timeframe", table_name="crypto_dataset_quality_scores")
    op.drop_index("ix_dataset_integrity_computed_at", table_name="dataset_integrity_scores")
    op.create_index(
        op.f("ix_dataset_integrity_scores_computed_at"),
        "dataset_integrity_scores",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_integrity_scores_dataset"),
        "dataset_integrity_scores",
        ["dataset"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dataset_integrity_scores_source"),
        "dataset_integrity_scores",
        ["source"],
        unique=False,
    )
    op.alter_column(
        "dataset_snapshots",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index("ix_dataset_snapshots_date", table_name="dataset_snapshots")
    op.create_index(
        op.f("ix_dataset_snapshots_dataset"), "dataset_snapshots", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_dataset_snapshots_snapshot_date"),
        "dataset_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    op.drop_index("ix_edge_alert_state_key", table_name="edge_alert_state")
    op.drop_index("ix_forward_shadow_signal_at", table_name="forward_shadow_signals")
    op.drop_index("ix_forward_shadow_symbol_tf", table_name="forward_shadow_signals")
    op.drop_index("ix_incident_events_id", table_name="incident_events")
    op.drop_index("ix_incident_events_service_severity", table_name="incident_events")
    op.drop_index("ix_incident_events_status_received", table_name="incident_events")
    op.drop_index(
        "ix_incident_events_unprocessed",
        table_name="incident_events",
        postgresql_where="(processed = false)",
    )
    op.drop_index("ix_ih_alert_id", table_name="incident_history")
    op.drop_index("ix_ih_event_id", table_name="incident_history")
    op.drop_index("ix_ih_recorded", table_name="incident_history")
    op.drop_index("ix_ih_root_cause", table_name="incident_history")
    op.drop_index("ix_ih_service", table_name="incident_history")
    op.create_index(
        op.f("ix_incident_history_alert_id"), "incident_history", ["alert_id"], unique=False
    )
    op.drop_constraint("incident_patterns_alert_id_key", "incident_patterns", type_="unique")
    op.drop_index("ix_ip_alert_id", table_name="incident_patterns")
    op.drop_index("ix_ip_flapping", table_name="incident_patterns")
    op.drop_index("ix_ip_mttr", table_name="incident_patterns")
    op.drop_index("ix_ip_service", table_name="incident_patterns")
    op.create_index(
        op.f("ix_incident_patterns_alert_id"), "incident_patterns", ["alert_id"], unique=True
    )
    op.alter_column(
        "observer_snapshot_runs",
        "classification",
        existing_type=sa.VARCHAR(length=24),
        comment="GO | GO_WITH_OBSERVATIONS | NO_GO",
        existing_nullable=False,
    )
    op.alter_column(
        "pipeline_failures",
        "error_type",
        existing_type=sa.VARCHAR(length=128),
        comment="Exception class name, e.g. 'UniqueViolation', 'TimeoutError'",
        existing_nullable=False,
    )
    op.alter_column(
        "pipeline_failures",
        "item_id",
        existing_type=sa.VARCHAR(length=256),
        comment="ID of the item that caused the failure (e.g. raw_collection.id)",
        existing_nullable=True,
    )
    op.alter_column(
        "pipeline_failures",
        "is_terminal",
        existing_type=sa.BOOLEAN(),
        comment="True when max retries exhausted (dead-letter equivalent for pipeline)",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.create_index(
        op.f("ix_pipeline_failures_occurred_at"), "pipeline_failures", ["occurred_at"], unique=False
    )
    op.alter_column(
        "pipeline_runs",
        "domain",
        existing_type=sa.VARCHAR(length=64),
        comment="Pipeline domain: crypto | ecommerce | real_estate | sports_betting | trading",
        existing_nullable=False,
    )
    op.alter_column(
        "pipeline_runs",
        "stage",
        existing_type=sa.VARCHAR(length=32),
        comment="Pipeline stage: collection | normalization | analytics",
        existing_nullable=False,
    )
    op.alter_column(
        "pipeline_runs",
        "status",
        existing_type=sa.VARCHAR(length=16),
        comment="running | success | partial | error",
        existing_nullable=False,
        existing_server_default=sa.text("'running'::character varying"),
    )
    op.alter_column(
        "pipeline_runs",
        "trigger",
        existing_type=sa.VARCHAR(length=32),
        comment="scheduler | api | manual",
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_pipeline_runs_source_name"), "pipeline_runs", ["source_name"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_runs_started_at"), "pipeline_runs", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_pipeline_runs_status"), "pipeline_runs", ["status"], unique=False)
    op.alter_column(
        "scraper_drift_events",
        "prev_signature",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "scraper_drift_events",
        "curr_signature",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_source_health_category"), "source_health", ["category"], unique=False)
    op.create_index(
        op.f("ix_source_health_collector_name"), "source_health", ["collector_name"], unique=False
    )
    op.alter_column(
        "telegram_publication_events",
        "status",
        existing_type=sa.VARCHAR(length=30),
        comment=None,
        existing_comment="sent | failed | rate_limited | skipped",
        existing_nullable=False,
    )
    op.alter_column(
        "telegram_publication_events",
        "reported_by",
        existing_type=sa.VARCHAR(length=64),
        comment="poupi-baby service identifier",
        existing_comment="poupi-baby service name",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_edge_outcomes", "horizon_hours", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "trading_edge_outcomes", "symbol", existing_type=sa.VARCHAR(length=40), nullable=False
    )
    op.alter_column(
        "trading_edge_outcomes", "timeframe", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "trading_edge_outcomes", "signal", existing_type=sa.VARCHAR(length=40), nullable=False
    )
    # Explicit USING clauses make this safe regardless of session timezone
    # config: naive values are interpreted as UTC wall-clock. Idempotent if
    # the column is already timestamptz in UTC (verified in production).
    op.alter_column(
        "trading_edge_outcomes",
        "signal_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        postgresql_using="signal_at AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        "trading_edge_outcomes",
        "outcome_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="outcome_at AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        "trading_edge_outcomes",
        "computed_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        postgresql_using="computed_at AT TIME ZONE 'UTC'",
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_trading_edge_outcomes_analytics_id "
        "ON trading_edge_outcomes (analytics_id)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_trading_edge_outcomes_outcome_correct "
        "ON trading_edge_outcomes (outcome_correct)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_trading_edge_outcomes_signal "
        "ON trading_edge_outcomes (signal)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_trading_edge_outcomes_signal_at "
        "ON trading_edge_outcomes (signal_at)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_trading_edge_outcomes_symbol "
        "ON trading_edge_outcomes (symbol)"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'trading_edge_outcomes'::regclass
                  AND conname = 'trading_edge_outcomes_analytics_id_fkey'
            )
            AND NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'trading_edge_outcomes'::regclass
                  AND conname = 'fk_trading_edge_outcomes_analytics_id_trading_analytics'
            ) THEN
                ALTER TABLE trading_edge_outcomes
                RENAME CONSTRAINT trading_edge_outcomes_analytics_id_fkey
                TO fk_trading_edge_outcomes_analytics_id_trading_analytics;
            ELSIF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'trading_edge_outcomes'::regclass
                  AND conname = 'fk_trading_edge_outcomes_analytics_id_trading_analytics'
            ) THEN
                ALTER TABLE trading_edge_outcomes
                ADD CONSTRAINT fk_trading_edge_outcomes_analytics_id_trading_analytics
                FOREIGN KEY (analytics_id)
                REFERENCES trading_analytics (id)
                ON DELETE SET NULL;
            END IF;
        END $$;
        """
    )
    op.alter_column(
        "trading_signal_outcomes",
        "analytics_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="FK → trading_analytics.id (unique: one outcome per signal)",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "signal",
        existing_type=sa.VARCHAR(length=40),
        comment=None,
        existing_comment="BUY | SELL",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "signal_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of signal candle",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "outcome_price",
        existing_type=sa.NUMERIC(precision=24, scale=8),
        comment="Close price at evaluation horizon",
        existing_comment="Close at evaluation horizon",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "price_change_pct",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        comment="(outcome_price - signal_price) / signal_price × 100",
        existing_comment="(outcome_price - signal_price) / signal_price * 100",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "max_favorable_pct",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        comment="MFE: max favourable excursion during horizon",
        existing_comment="MFE: max favorable excursion",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "max_adverse_pct",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        comment="MAE: max adverse excursion during horizon",
        existing_comment="MAE: max adverse excursion",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "outcome_correct",
        existing_type=sa.BOOLEAN(),
        comment="True when price moved in the signal direction",
        existing_comment="BUY && price_change>0, SELL && price_change<0",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "evaluation_horizon_candles",
        existing_type=sa.INTEGER(),
        comment="Number of subsequent candles used for evaluation",
        existing_comment="How many candles ahead was outcome evaluated",
        existing_nullable=False,
        existing_server_default=sa.text("6"),
    )
    op.drop_index("ix_signal_outcomes_symbol_tf_at", table_name="trading_signal_outcomes")
    op.drop_index(
        "ix_uel_active",
        table_name="universal_executions",
        postgresql_where="((status)::text = ANY ((ARRAY['planned'::character varying, 'approved'::character varying, 'running'::character varying])::text[]))",  # noqa: E501
    )
    op.drop_index("ix_uel_actor", table_name="universal_executions")
    op.drop_index("ix_uel_capability_id", table_name="universal_executions")
    op.drop_index("ix_uel_correlation_id", table_name="universal_executions")
    op.drop_index("ix_uel_mission_id", table_name="universal_executions")
    op.drop_index("ix_uel_parent_execution_id", table_name="universal_executions")
    op.drop_index("ix_uel_project_id", table_name="universal_executions")
    op.drop_index("ix_uel_status", table_name="universal_executions")
    op.drop_index("ix_uel_timestamp", table_name="universal_executions")
    op.drop_index("uq_uel_execution_id", table_name="universal_executions")
    op.create_index("ix_uel_correlation", "universal_executions", ["correlation_id"], unique=False)
    op.create_index("ix_uel_parent", "universal_executions", ["parent_execution_id"], unique=False)
    op.create_index(
        op.f("ix_universal_executions_actor"), "universal_executions", ["actor"], unique=False
    )
    op.create_index(
        op.f("ix_universal_executions_capability_id"),
        "universal_executions",
        ["capability_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_correlation_id"),
        "universal_executions",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_execution_id"),
        "universal_executions",
        ["execution_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_universal_executions_execution_surface"),
        "universal_executions",
        ["execution_surface"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_execution_type"),
        "universal_executions",
        ["execution_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_executor"), "universal_executions", ["executor"], unique=False
    )
    op.create_index(
        op.f("ix_universal_executions_mission_id"),
        "universal_executions",
        ["mission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_parent_execution_id"),
        "universal_executions",
        ["parent_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_portfolio_id"),
        "universal_executions",
        ["portfolio_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_project_id"),
        "universal_executions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_schema_version"),
        "universal_executions",
        ["schema_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_universal_executions_status"), "universal_executions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_universal_executions_timestamp"),
        "universal_executions",
        ["timestamp"],
        unique=False,
    )
    op.alter_column(
        "watchdog_runs",
        "check_results",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "watchdog_runs",
        "alert_codes",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "watchdog_runs",
        "metrics_snapshot",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_constraint("wnba_edge_registry_setup_name_key", "wnba_edge_registry", type_="unique")
    op.drop_index("ix_wnba_edge_registry_setup_name", table_name="wnba_edge_registry")
    op.create_index(
        op.f("ix_wnba_edge_registry_setup_name"), "wnba_edge_registry", ["setup_name"], unique=True
    )
    op.drop_constraint("wnba_features_game_id_key", "wnba_features", type_="unique")
    op.drop_index("ix_wnba_features_game_id", table_name="wnba_features")
    op.create_index(op.f("ix_wnba_features_game_id"), "wnba_features", ["game_id"], unique=True)
    op.drop_constraint("wnba_quant_bets_signal_id_key", "wnba_quant_bets", type_="unique")
    op.drop_index("ix_wnba_quant_bets_signal_id", table_name="wnba_quant_bets")
    op.create_index(
        op.f("ix_wnba_quant_bets_signal_id"), "wnba_quant_bets", ["signal_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wnba_quant_bets_signal_id"), table_name="wnba_quant_bets")
    op.create_index("ix_wnba_quant_bets_signal_id", "wnba_quant_bets", ["signal_id"], unique=False)
    op.create_unique_constraint("wnba_quant_bets_signal_id_key", "wnba_quant_bets", ["signal_id"])
    op.drop_index(op.f("ix_wnba_features_game_id"), table_name="wnba_features")
    op.create_index("ix_wnba_features_game_id", "wnba_features", ["game_id"], unique=False)
    op.create_unique_constraint("wnba_features_game_id_key", "wnba_features", ["game_id"])
    op.drop_index(op.f("ix_wnba_edge_registry_setup_name"), table_name="wnba_edge_registry")
    op.create_index(
        "ix_wnba_edge_registry_setup_name", "wnba_edge_registry", ["setup_name"], unique=False
    )
    op.create_unique_constraint(
        "wnba_edge_registry_setup_name_key", "wnba_edge_registry", ["setup_name"]
    )
    op.alter_column(
        "watchdog_runs",
        "metrics_snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "watchdog_runs",
        "alert_codes",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "watchdog_runs",
        "check_results",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_universal_executions_timestamp"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_status"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_schema_version"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_project_id"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_portfolio_id"), table_name="universal_executions")
    op.drop_index(
        op.f("ix_universal_executions_parent_execution_id"), table_name="universal_executions"
    )
    op.drop_index(op.f("ix_universal_executions_mission_id"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_executor"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_execution_type"), table_name="universal_executions")
    op.drop_index(
        op.f("ix_universal_executions_execution_surface"), table_name="universal_executions"
    )
    op.drop_index(op.f("ix_universal_executions_execution_id"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_correlation_id"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_capability_id"), table_name="universal_executions")
    op.drop_index(op.f("ix_universal_executions_actor"), table_name="universal_executions")
    op.drop_index("ix_uel_parent", table_name="universal_executions")
    op.drop_index("ix_uel_correlation", table_name="universal_executions")
    op.create_index("uq_uel_execution_id", "universal_executions", ["execution_id"], unique=True)
    op.create_index("ix_uel_timestamp", "universal_executions", ["timestamp"], unique=False)
    op.create_index("ix_uel_status", "universal_executions", ["status"], unique=False)
    op.create_index("ix_uel_project_id", "universal_executions", ["project_id"], unique=False)
    op.create_index(
        "ix_uel_parent_execution_id", "universal_executions", ["parent_execution_id"], unique=False
    )
    op.create_index("ix_uel_mission_id", "universal_executions", ["mission_id"], unique=False)
    op.create_index(
        "ix_uel_correlation_id", "universal_executions", ["correlation_id"], unique=False
    )
    op.create_index("ix_uel_capability_id", "universal_executions", ["capability_id"], unique=False)
    op.create_index("ix_uel_actor", "universal_executions", ["actor"], unique=False)
    op.create_index(
        "ix_uel_active",
        "universal_executions",
        ["project_id", "timestamp"],
        unique=False,
        postgresql_where="((status)::text = ANY ((ARRAY['planned'::character varying, 'approved'::character varying, 'running'::character varying])::text[]))",  # noqa: E501
    )
    op.create_index(
        "ix_signal_outcomes_symbol_tf_at",
        "trading_signal_outcomes",
        ["symbol", "timeframe", "signal_at"],
        unique=False,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "evaluation_horizon_candles",
        existing_type=sa.INTEGER(),
        comment="How many candles ahead was outcome evaluated",
        existing_comment="Number of subsequent candles used for evaluation",
        existing_nullable=False,
        existing_server_default=sa.text("6"),
    )
    op.alter_column(
        "trading_signal_outcomes",
        "outcome_correct",
        existing_type=sa.BOOLEAN(),
        comment="BUY && price_change>0, SELL && price_change<0",
        existing_comment="True when price moved in the signal direction",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "max_adverse_pct",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        comment="MAE: max adverse excursion",
        existing_comment="MAE: max adverse excursion during horizon",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "max_favorable_pct",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        comment="MFE: max favorable excursion",
        existing_comment="MFE: max favourable excursion during horizon",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "price_change_pct",
        existing_type=sa.NUMERIC(precision=10, scale=4),
        comment="(outcome_price - signal_price) / signal_price * 100",
        existing_comment="(outcome_price - signal_price) / signal_price × 100",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "outcome_price",
        existing_type=sa.NUMERIC(precision=24, scale=8),
        comment="Close at evaluation horizon",
        existing_comment="Close price at evaluation horizon",
        existing_nullable=True,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "signal_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of signal candle",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "signal",
        existing_type=sa.VARCHAR(length=40),
        comment="BUY | SELL",
        existing_nullable=False,
    )
    op.alter_column(
        "trading_signal_outcomes",
        "analytics_id",
        existing_type=sa.UUID(),
        comment="FK → trading_analytics.id (unique: one outcome per signal)",
        existing_nullable=True,
    )
    op.drop_constraint(
        "fk_trading_edge_outcomes_analytics_id_trading_analytics",
        "trading_edge_outcomes",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_trading_edge_outcomes_symbol"), table_name="trading_edge_outcomes")
    op.drop_index(op.f("ix_trading_edge_outcomes_signal_at"), table_name="trading_edge_outcomes")
    op.drop_index(op.f("ix_trading_edge_outcomes_signal"), table_name="trading_edge_outcomes")
    op.drop_index(
        op.f("ix_trading_edge_outcomes_outcome_correct"), table_name="trading_edge_outcomes"
    )
    op.drop_index(op.f("ix_trading_edge_outcomes_analytics_id"), table_name="trading_edge_outcomes")
    op.alter_column(
        "trading_edge_outcomes",
        "computed_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "trading_edge_outcomes",
        "outcome_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "trading_edge_outcomes",
        "signal_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "trading_edge_outcomes", "signal", existing_type=sa.VARCHAR(length=40), nullable=True
    )
    op.alter_column(
        "trading_edge_outcomes", "timeframe", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    op.alter_column(
        "trading_edge_outcomes", "symbol", existing_type=sa.VARCHAR(length=40), nullable=True
    )
    op.alter_column(
        "trading_edge_outcomes", "horizon_hours", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "telegram_publication_events",
        "reported_by",
        existing_type=sa.VARCHAR(length=64),
        comment="poupi-baby service name",
        existing_comment="poupi-baby service identifier",
        existing_nullable=True,
    )
    op.alter_column(
        "telegram_publication_events",
        "status",
        existing_type=sa.VARCHAR(length=30),
        comment="sent | failed | rate_limited | skipped",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_source_health_collector_name"), table_name="source_health")
    op.drop_index(op.f("ix_source_health_category"), table_name="source_health")
    op.alter_column(
        "scraper_drift_events",
        "curr_signature",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "scraper_drift_events",
        "prev_signature",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_pipeline_runs_status"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_started_at"), table_name="pipeline_runs")
    op.drop_index(op.f("ix_pipeline_runs_source_name"), table_name="pipeline_runs")
    op.alter_column(
        "pipeline_runs",
        "trigger",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="scheduler | api | manual",
        existing_nullable=True,
    )
    op.alter_column(
        "pipeline_runs",
        "status",
        existing_type=sa.VARCHAR(length=16),
        comment=None,
        existing_comment="running | success | partial | error",
        existing_nullable=False,
        existing_server_default=sa.text("'running'::character varying"),
    )
    op.alter_column(
        "pipeline_runs",
        "stage",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="Pipeline stage: collection | normalization | analytics",
        existing_nullable=False,
    )
    op.alter_column(
        "pipeline_runs",
        "domain",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="Pipeline domain: crypto | ecommerce | real_estate | sports_betting | trading",  # noqa: E501
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_pipeline_failures_occurred_at"), table_name="pipeline_failures")
    op.alter_column(
        "pipeline_failures",
        "is_terminal",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="True when max retries exhausted (dead-letter equivalent for pipeline)",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "pipeline_failures",
        "item_id",
        existing_type=sa.VARCHAR(length=256),
        comment=None,
        existing_comment="ID of the item that caused the failure (e.g. raw_collection.id)",
        existing_nullable=True,
    )
    op.alter_column(
        "pipeline_failures",
        "error_type",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="Exception class name, e.g. 'UniqueViolation', 'TimeoutError'",
        existing_nullable=False,
    )
    op.alter_column(
        "observer_snapshot_runs",
        "classification",
        existing_type=sa.VARCHAR(length=24),
        comment=None,
        existing_comment="GO | GO_WITH_OBSERVATIONS | NO_GO",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_incident_patterns_alert_id"), table_name="incident_patterns")
    op.create_index("ix_ip_service", "incident_patterns", ["service"], unique=False)
    op.create_index("ix_ip_mttr", "incident_patterns", ["mttr_seconds"], unique=False)
    op.create_index("ix_ip_flapping", "incident_patterns", ["is_flapping"], unique=False)
    op.create_index("ix_ip_alert_id", "incident_patterns", ["alert_id"], unique=True)
    op.create_unique_constraint("incident_patterns_alert_id_key", "incident_patterns", ["alert_id"])
    op.drop_index(op.f("ix_incident_history_alert_id"), table_name="incident_history")
    op.create_index("ix_ih_service", "incident_history", ["service"], unique=False)
    op.create_index("ix_ih_root_cause", "incident_history", ["root_cause_bucket"], unique=False)
    op.create_index("ix_ih_recorded", "incident_history", ["recorded_at"], unique=False)
    op.create_index("ix_ih_event_id", "incident_history", ["incident_event_id"], unique=False)
    op.create_index("ix_ih_alert_id", "incident_history", ["alert_id"], unique=False)
    op.create_index(
        "ix_incident_events_unprocessed",
        "incident_events",
        ["processed", "received_at"],
        unique=False,
        postgresql_where="(processed = false)",
    )
    op.create_index(
        "ix_incident_events_status_received",
        "incident_events",
        ["status", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_incident_events_service_severity",
        "incident_events",
        ["service", "severity"],
        unique=False,
    )
    op.create_index("ix_incident_events_id", "incident_events", ["id"], unique=False)
    op.create_index(
        "ix_forward_shadow_symbol_tf",
        "forward_shadow_signals",
        ["symbol", "timeframe"],
        unique=False,
    )
    op.create_index(
        "ix_forward_shadow_signal_at", "forward_shadow_signals", ["signal_at"], unique=False
    )
    op.create_index("ix_edge_alert_state_key", "edge_alert_state", ["alert_key"], unique=True)
    op.drop_index(op.f("ix_dataset_snapshots_snapshot_date"), table_name="dataset_snapshots")
    op.drop_index(op.f("ix_dataset_snapshots_dataset"), table_name="dataset_snapshots")
    op.create_index(
        "ix_dataset_snapshots_date", "dataset_snapshots", ["snapshot_date"], unique=False
    )
    op.alter_column(
        "dataset_snapshots",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_dataset_integrity_scores_source"), table_name="dataset_integrity_scores")
    op.drop_index(
        op.f("ix_dataset_integrity_scores_dataset"), table_name="dataset_integrity_scores"
    )
    op.drop_index(
        op.f("ix_dataset_integrity_scores_computed_at"), table_name="dataset_integrity_scores"
    )
    op.create_index(
        "ix_dataset_integrity_computed_at",
        "dataset_integrity_scores",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        "ix_crypto_dq_symbol_timeframe",
        "crypto_dataset_quality_scores",
        ["symbol", "timeframe"],
        unique=False,
    )
    op.alter_column(
        "crypto_dataset_quality_scores",
        "gap_count",
        existing_type=sa.INTEGER(),
        comment="Missing intervals in last 24h",
        existing_nullable=True,
    )
    op.alter_column(
        "crypto_dataset_quality_scores",
        "coverage_pct",
        existing_type=sa.NUMERIC(precision=6, scale=2),
        comment="% of expected candles in 24h",
        existing_nullable=True,
    )
    op.alter_column(
        "crypto_dataset_quality_scores",
        "staleness_hours",
        existing_type=sa.NUMERIC(precision=8, scale=2),
        comment="Hours since last candle",
        existing_nullable=True,
    )
    op.alter_column(
        "crypto_dataset_quality_scores",
        "integrity_score",
        existing_type=sa.NUMERIC(precision=6, scale=2),
        comment="0-100 composite score",
        existing_nullable=True,
    )
    op.alter_column(
        "collector_errors",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "collector_definitions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "collector_definitions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "collection_runs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "collected_records",
        "collected_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###
